### PR TITLE
HCX-743: Nginx configuration for exporting metrics added prometheus.conf in config.yml & changes made in service.yml,deplyment.yml in hcx-Devops

### PR DESCRIPTION
**Pull request by nagoorbasha7869**
I have made changes in files please review it once everything is fine merge it to sprint-40.

### CODE REVIEW

**Review by nagoorbasha7869 — COMMENTED** [review]
@maheshkumargangula Please review my changes and merge it ito sprint-40

**Comment by maheshkumargangula** [comment]
@nagoorbasha7869 – Please mention the JIRA ticket details in the PR title and description.

**Comment by nagoorbasha7869** [comment]
> @nagoorbasha7869 – Please mention the JIRA ticket details in the PR title and description.

I don't have JIRA access @maheshkumargangula

**Comment by nagoorbasha7869** [comment]
> > @nagoorbasha7869 – Please mention the JIRA ticket details in the PR title and description.
> 
> I don't have JIRA access @maheshkumargangula

@maheshkumargangula , I have created a ticket in JIRA can you please check once?

**Review by maheshkumargangula — APPROVED** [review]

**Review by maheshkumargangula — APPROVED** [review]

**Pull request merged**
